In [7]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from seaborn import regplot
import matplotlib.pyplot as plt
%matplotlib inline

## Which feature below is most predictive of fuel economy? Use the data set *Auto-cleaned.csv* and simple linear regression using each feature (one at a time) to predict fuel economy. Rank the features by (training) R_squared. The method *.score* gives R_squared values.

In [15]:
df = pd.read_csv("./Auto-cleaned.csv")
df = df.drop(columns='Unnamed: 0',axis=0)
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,1,ford torino

In [21]:
feature_name=[]
R2=[]
target = df.mpg
for k in range(7):
    lr = LinearRegression()
    feature_name.append(df.columns[k])
    feature = df.iloc[:,k]
    lr.fit(feature.values.reshape(-1,1),target)
    R2.append(lr.score(feature.values.reshape(-1,1),target))
    
error = pd.DataFrame()
error['Feature'] = feature_name
error['Rsquared'] = R2

error.sort_values('Rsquared', ascending=False).round(5)

        Feature  Rsquared
0           mpg   1.00000
4        weight   0.69263
2  displacement   0.64823
3    horsepower   0.60595
1     cylinders   0.60469
6          year   0.33703
5  acceleration   0.17921

Ranked from best to worst predictor of fuel economy:

weight

displacement

horsepower

cylinders

year

acceleration