In [1]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.svm import SVR
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_validate, GridSearchCV
%matplotlib inline

In [2]:
df = pd.read_csv("./tips.csv")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [3]:
target = df.tip
features = df.drop('tip',axis=1)
features = pd.get_dummies(df)
features = (features - features.mean()) / features.std()
features.head()

,total_bill,tip,size,sex_Female,sex_Male,smoker_No,smoker_Yes,day_Fri,day_Sat,day_Sun,day_Thur,time_Dinner,time_Lunch
0,-0.314066,-1.436993,-0.598961,1.340598,-1.340598,0.783179,-0.783179,-0.289997,-0.742879,1.483734,-0.582463,0.620307,-0.620307
1,-1.061054,-0.967217,0.452453,-0.742879,0.742879,0.783179,-0.783179,-0.289997,-0.742879,1.483734,-0.582463,0.620307,-0.620307
2,0.137497,0.362610,0.452453,-0.742879,0.742879,0.783179,-0.783179,-0.289997,-0.742879,1.483734,-0.582463,0.620307,-0.620307
3,0.437416,0.225291,-0.598961,-0.742879,0.742879,0.783179,-0.783179,-0.289997,-0.742879,1.483734,-0.582463,0.620307,-0.620307
4,0.539635,0.442111,1.503867,1.340598,-1.340598,0.783179,-0.783179,-0.289997,-0.742879,1.483734,-0.582463,0.620307,-0.620307

In [4]:
grid = {'C': np.linspace(100,400,10)}

clf = SVR()
clfCV = GridSearchCV(clf,param_grid=grid,return_train_score=True,n_jobs=-1)
clfCV.fit(features,target)

print()
print('parameters = ', clfCV.best_params_, 'validation R2 = ', clfCV.best_score_.round(3))

C:\Users\rileyma\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)

parameters =  {'C': 100.0} validation R2 =  0.896

C:\Users\rileyma\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)
C:\Users\rileyma\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

In [5]:
target = df.tip
features = df.drop('tip',axis=1)
features = pd.get_dummies(df)
features = (features - features.mean()) / features.std()
features.head()

,total_bill,tip,size,sex_Female,sex_Male,smoker_No,smoker_Yes,day_Fri,day_Sat,day_Sun,day_Thur,time_Dinner,time_Lunch
0,-0.314066,-1.436993,-0.598961,1.340598,-1.340598,0.783179,-0.783179,-0.289997,-0.742879,1.483734,-0.582463,0.620307,-0.620307
1,-1.061054,-0.967217,0.452453,-0.742879,0.742879,0.783179,-0.783179,-0.289997,-0.742879,1.483734,-0.582463,0.620307,-0.620307
2,0.137497,0.362610,0.452453,-0.742879,0.742879,0.783179,-0.783179,-0.289997,-0.742879,1.483734,-0.582463,0.620307,-0.620307
3,0.437416,0.225291,-0.598961,-0.742879,0.742879,0.783179,-0.783179,-0.289997,-0.742879,1.483734,-0.582463,0.620307,-0.620307
4,0.539635,0.442111,1.503867,1.340598,-1.340598,0.783179,-0.783179,-0.289997,-0.742879,1.483734,-0.582463,0.620307,-0.620307

In [6]:
grid = {'C': [0.01,0.1,1,10,100,1000,10000]}

clf = SVR()
clfCV = GridSearchCV(clf,param_grid=grid,return_train_score=True,n_jobs=-1)
clfCV.fit(features,target)

print()
print('parameters = ', clfCV.best_params_, 'validation R2 = ', clfCV.best_score_.round(3))
print('training R2 = ', clfCV.best_estimator_.score(features,target).round(3))

parameters =  {'C': 10} validation R2 =  0.896
training R2 =  0.997

C:\Users\rileyma\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\rileyma\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)
C:\Users\rileyma\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)